apiVersion: v2
name: mern-app
description: A Helm chart for MERN Stack Application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mongodb
    version: "0.1.0"
    repository: "file://charts/mongodb"
  - name: server
    version: "0.1.0"
    repository: "file://charts/server"
  - name: client
    version: "0.1.0"
    repository: "file://charts/client"